# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yago < Formula
  desc "Yago is a GitOps tool for non-kubernetes platforms"
  homepage "https://github.com/danieleborsaro/homebrew-devops"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "8646e6b90244227bb6b84e19e16c03ce4ddf862139a037571ff8fe1a81544c40"

      define_method(:install) do
        bin.install "yago"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Darwin_arm64.tar.gz"
      sha256 "2b95207f46cfe9e38a4db3abb17bb0d4ca098f69aa2089ceaf65c19ea7071df7"

      define_method(:install) do
        bin.install "yago"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Linux_x86_64.tar.gz"
      sha256 "bb174a154391483831e7885d6fc7d8edefd981666d2b409a54859f0be625c59a"
      define_method(:install) do
        bin.install "yago"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Linux_arm64.tar.gz"
      sha256 "9bf8a7ffa78e0db6ce7a3b546bad440be4bc1a8f1c23a4ada769667c4c70807e"
      define_method(:install) do
        bin.install "yago"
      end
    end
  end
end
