# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yago < Formula
  desc "Yago is a GitOps tool for non-kubernetes platforms"
  homepage "https://github.com/danieleborsaro/homebrew-devops"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "441b0f73005fe96953d503dc0cd53efcb69b5254cc217c1a0bc353992b57c332"

      define_method(:install) do
        bin.install "yago"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Darwin_arm64.tar.gz"
      sha256 "0d061495444fb033607f2ce7c5801a14e66c5574cc285870b677e69e006946ca"

      define_method(:install) do
        bin.install "yago"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Linux_x86_64.tar.gz"
      sha256 "ef7b1c1935a8e070f46364f905c761837f230759bdd8827db8cb50b081dd8e98"
      define_method(:install) do
        bin.install "yago"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieleborsaro/yago/releases/download/v0.2.3/yago_0.2.3_Linux_arm64.tar.gz"
      sha256 "6f4395ebc6bf16ccf5c3caf82a9d2362730b868d23a34463590e131f87d9f56c"
      define_method(:install) do
        bin.install "yago"
      end
    end
  end
end
